In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\ADMIN\Desktop\Superstore sales dataset.csv")

In [3]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [4]:
df.shape

(9994, 21)

In [5]:
import pandas as pd
pd.DataFrame([1,2,3],columns=['P'],index=['A','B','C'])

   P
A  1
B  2
C  3

In [6]:
import pandas as pd 
pd.DataFrame([[2,4,5],[1,5,6],[9,7,5]],columns=['A','B','C'],index=['B','C','D'])

   A  B  C
B  2  4  5
C  1  5  6
D  9  7  5

In [7]:
pd.DataFrame((1,2,3))

   0
0  1
1  2
2  3

In [8]:
pd.DataFrame(((1,2,3),(4,5,6)))

   0  1  2
0  1  2  3
1  4  5  6

In [9]:
pd.DataFrame({"months":["jan","feb"],"sales":[20,40]})

  months  sales
0    jan     20
1    feb     40

In [10]:
pd.DataFrame({"ipl-rcb":["2009","2011","2016","2025"],"results":["runner_up","runner_up","runner_up","winners"],"opponent":["deccan_charges","csk","srh","punjab"]})

  ipl-rcb    results        opponent
0    2009  runner_up  deccan_charges
1    2011  runner_up             csk
2    2016  runner_up             srh
3    2025    winners          punjab

In [11]:
"A B C".split()

['A', 'B', 'C']

In [12]:
import pandas as pd
import numpy as np
np.random.seed(121)
df=pd.DataFrame(np.random.randint(0,10,(3,3)),columns="A B C".split(),index="P Q R".split())

In [13]:
df

   A  B  C
P  2  5  8
Q  4  1  4
R  3  0  2

In [14]:
import pandas as pd
df=pd.read_csv(r"C:\Users\ADMIN\Downloads\Superstore sales dataset.csv")

In [15]:
df.shape

(9994, 21)

In [16]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [17]:
df.tail(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [18]:
df.index

RangeIndex(start=0, stop=9994, step=1)

In [19]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [35]:
df.['ROW ID']

SyntaxError: invalid syntax (4031426869.py, line 1)

In [ ]:
import pandas as pd
df=pd.read_csv(r"C:\Users\ADMIN\Downloads\Superstore sales dataset.csv")

In [36]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [ ]:
df.index

RangeIndex(start=0, stop=9994, step=1)

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
df[["Row ID","Order ID"]].head(2)

   Row ID        Order ID
0       1  CA-2016-152156
1       2  CA-2016-152156

In [ ]:
df.iloc[rows,columns]

NameError: name 'rows' is not defined

In [ ]:
df.iloc[2:8,[2,5,8,4]]           ## integer location based index.it is used to access the rows and columns position

   Order Date Customer ID        Country       Ship Mode
2   12/6/2016    DV-13045  United States    Second Class
3  11/10/2015    SO-20335  United States  Standard Class
4  11/10/2015    SO-20335  United States  Standard Class
5    9/6/2014    BH-11710  United States  Standard Class
6    9/6/2014    BH-11710  United States  Standard Class
7    9/6/2014    BH-11710  United States  Standard Class

In [ ]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [ ]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [ ]:
import numpy as np
np.iinfo(np.int8)
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [ ]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [ ]:
np.finfo(np.float16).min

np.float16(-6.55e+04)

In [ ]:
np.finfo(np.float16).max

np.float16(6.55e+04)

In [38]:
np.finfo(np.float16).bits
np.finfo(np.float64).bits

64

In [ ]:
np.finfo(np.float16).dtype

dtype('float16')

In [40]:
df.select_dtypes(include=['int64','float64']).head(2)

   Row ID  Postal Code   Sales  Quantity  Discount    Profit
0       1        42420  261.96         2       0.0   41.9136
1       2        42420  731.94         3       0.0  219.5820

In [ ]:
df.select_dtypes(include='number')

      Row ID  Postal Code     Sales  Quantity  Discount    Profit
0          1        42420  261.9600         2      0.00   41.9136
1          2        42420  731.9400         3      0.00  219.5820
2          3        90036   14.6200         2      0.00    6.8714
3          4        33311  957.5775         5      0.45 -383.0310
4          5        33311   22.3680         2      0.20    2.5164
...      ...          ...       ...       ...       ...       ...
9989    9990        33180   25.2480         3      0.20    4.1028
9990    9991        92627   91.9600         2      0.00   15.6332
9991    9992        92627  258.5760         2      0.20   19.3932
9992    9993        92627   29.6000         4      0.00   13.3200
9993    9994        92683  243.1600         2      0.00   72.9480

[9994 rows x 6 columns]

In [47]:
df.select_dtypes(include=['int8','int16','int32','float16']).head(2)  ## because there is these types of data dypes.that's why getting no result

Empty DataFrame
Columns: []
Index: [0, 1]

In [46]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [45]:
df.select_dtypes(include=['object']).shape

(9994, 15)

In [ ]:
df.shape

(9994, 21)

In [49]:
df.select_dtypes(include=['int8','float16']).shape

(9994, 0)

In [50]:
df.select_dtypes(include=['int64','float64'])

      Row ID  Postal Code     Sales  Quantity  Discount    Profit
0          1        42420  261.9600         2      0.00   41.9136
1          2        42420  731.9400         3      0.00  219.5820
2          3        90036   14.6200         2      0.00    6.8714
3          4        33311  957.5775         5      0.45 -383.0310
4          5        33311   22.3680         2      0.20    2.5164
...      ...          ...       ...       ...       ...       ...
9989    9990        33180   25.2480         3      0.20    4.1028
9990    9991        92627   91.9600         2      0.00   15.6332
9991    9992        92627  258.5760         2      0.20   19.3932
9992    9993        92627   29.6000         4      0.00   13.3200
9993    9994        92683  243.1600         2      0.00   72.9480

[9994 rows x 6 columns]

In [ ]:
subset_df=df.iloc[0:5,0:5].copy()

In [ ]:
subset_df

   Row ID        Order ID  Order Date   Ship Date       Ship Mode
0       1  CA-2016-152156   8/11/2016  11/11/2016    Second Class
1       2  CA-2016-152156   8/11/2016  11/11/2016    Second Class
2       3  CA-2016-138688   12/6/2016   16/6/2016    Second Class
3       4  US-2015-108966  11/10/2015  18/10/2015  Standard Class
4       5  US-2015-108966  11/10/2015  18/10/2015  Standard Class

In [ ]:
df.iloc[0:5,0:5].copy()

   Row ID        Order ID  Order Date   Ship Date       Ship Mode
0       1  CA-2016-152156   8/11/2016  11/11/2016    Second Class
1       2  CA-2016-152156   8/11/2016  11/11/2016    Second Class
2       3  CA-2016-138688   12/6/2016   16/6/2016    Second Class
3       4  US-2015-108966  11/10/2015  18/10/2015  Standard Class
4       5  US-2015-108966  11/10/2015  18/10/2015  Standard Class

In [51]:
df.iloc[3:9,3:5]

    Ship Date       Ship Mode
3  18/10/2015  Standard Class
4  18/10/2015  Standard Class
5   14/6/2014  Standard Class
6   14/6/2014  Standard Class
7   14/6/2014  Standard Class
8   14/6/2014  Standard Class

In [ ]:
df.iloc[0:5,0:5].copy().shape

(5, 5)

In [ ]:
subset_df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode'], dtype='object')

In [55]:
df[['Row ID','Order ID']].min()

Row ID                   1
Order ID    CA-2014-100006
dtype: object

In [56]:
df[['Row ID','Order ID','Ship Date']].min()

Row ID                    1
Order ID     CA-2014-100006
Ship Date          1/1/2015
dtype: object

In [ ]:
subset_df[['Row ID','Order ID']].min()     ## case sensetive must

Row ID                   1
Order ID    CA-2016-138688
dtype: object

In [ ]:
subset_df[['Row ID']].min()

Row ID    1
dtype: int64

In [ ]:
df[['Sales']].mean()

Sales    229.858001
dtype: float64

In [ ]:
df['Ship Mode'].str.upper().head(8)

0      SECOND CLASS
1      SECOND CLASS
2      SECOND CLASS
3    STANDARD CLASS
4    STANDARD CLASS
5    STANDARD CLASS
6    STANDARD CLASS
7    STANDARD CLASS
Name: Ship Mode, dtype: object

In [ ]:
df['Ship Mode'].str.lower().head(8)

0      second class
1      second class
2      second class
3    standard class
4    standard class
5    standard class
6    standard class
7    standard class
Name: Ship Mode, dtype: object

In [ ]:
df['Ship Mode'].str.title().head(8)

0      Second Class
1      Second Class
2      Second Class
3    Standard Class
4    Standard Class
5    Standard Class
6    Standard Class
7    Standard Class
Name: Ship Mode, dtype: object

In [ ]:
df['Ship Mode'].str.capitalize().head(8)

0      Second class
1      Second class
2      Second class
3    Standard class
4    Standard class
5    Standard class
6    Standard class
7    Standard class
Name: Ship Mode, dtype: object

In [ ]:
df['Ship Mode'].str.len().tail(5)

9989    12
9990    14
9991    14
9992    14
9993    12
Name: Ship Mode, dtype: int64

In [58]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [61]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [72]:
df[['Customer Name','Product Name']].str.lower()

AttributeError: 'DataFrame' object has no attribute 'str'

In [ ]:
df['Ship Mode'].str.strip().head()

0      Second Class
1      Second Class
2      Second Class
3    Standard Class
4    Standard Class
Name: Ship Mode, dtype: object

In [ ]:
df['Ship Mode'].str.lstrip().head()

0      Second Class
1      Second Class
2      Second Class
3    Standard Class
4    Standard Class
Name: Ship Mode, dtype: object

In [ ]:
df['Ship Mode'].str.split(" ").head().str[1]

0    Class
1    Class
2    Class
3    Class
4    Class
Name: Ship Mode, dtype: object

In [ ]:
df['Ship Mode'].str.split(" ").head().str[0]

0      Second
1      Second
2      Second
3    Standard
4    Standard
Name: Ship Mode, dtype: object

In [ ]:
"9838-498346".split("3")

['98', '8-498', '46']

In [ ]:
df['Ship Mode'].str.count("Class").head(3)

0    1
1    1
2    1
Name: Ship Mode, dtype: int64

In [ ]:
df["Ship Mode"].str.pad(width=26,side='left',fillchar='5')

0       55555555555555Second Class
1       55555555555555Second Class
2       55555555555555Second Class
3       555555555555Standard Class
4       555555555555Standard Class
                   ...
9989    55555555555555Second Class
9990    555555555555Standard Class
9991    555555555555Standard Class
9992    555555555555Standard Class
9993    55555555555555Second Class
Name: Ship Mode, Length: 9994, dtype: object

In [ ]:
df["Customer Name"].str.pad(width=18,side='right',fillchar='&').head(2)

0    Claire Gute&&&&&&&
1    Claire Gute&&&&&&&
Name: Customer Name, dtype: object

In [ ]:
import pandas as pd
import numpy as np

# Retail Dataset
data = pd.DataFrame({
    "Order_ID": ["CA-1001", "CA-1002", "CA-1003", "CA-1004"],
    "Customer_Name": ["John", np.nan, "David", "Maria"],
    "Region": ["South", "East", np.nan, "West"],
    "Category": ["Furniture", "Technology", "Office Supplies", np.nan],
    "Sales": [2500, np.nan, 1800, 3200],
    "Profit": [200, 350, np.nan, 500],
    "Discount": [0.10, np.nan, 0.20, 0.15],
    "Quantity": [2, 3, np.nan, 5]
})

In [ ]:
import pandas as pd
sales_data=pd.DataFrame(data)

In [ ]:
sales_data

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,NaN,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

In [ ]:
sales_data.isna()

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,False,False,False,False,False,False,False,False
1,False,True,False,False,True,False,True,False
2,False,False,True,False,False,True,False,True
3,False,False,False,True,False,False,False,False

In [ ]:
sales_data.isna().sum()

Order_ID         0
Customer_Name    1
Region           1
Category         1
Sales            1
Profit           1
Discount         1
Quantity         1
dtype: int64

In [ ]:
null_values_percentage=(sales_data.isna().sum()/sales_data.shape[0])*100

In [ ]:
sales_data.shape[0]      ## getting no.of rows i.e 4

4

In [ ]:
null_values_percentage

Order_ID          0.0
Customer_Name    25.0
Region           25.0
Category         25.0
Sales            25.0
Profit           25.0
Discount         25.0
Quantity         25.0
dtype: float64

In [ ]:
null_values_percentage>=25 ## threshold value 25 its not fix its an optional

Order_ID         False
Customer_Name     True
Region            True
Category          True
Sales             True
Profit            True
Discount          True
Quantity          True
dtype: bool

In [ ]:
null_values_percentage[null_values_percentage>=25].index          ## gives all columns that have null values have >=25

Index(['Customer_Name', 'Region', 'Category', 'Sales', 'Profit', 'Discount',
       'Quantity'],
      dtype='object')

In [ ]:
null_values_percentage[null_values_percentage<25].index

Index(['Order_ID'], dtype='object')

## fillna     and      dropna

In [ ]:
sales_data

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,NaN,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

In [ ]:
mean_value=sales_data['Sales'].mean()

In [ ]:
mean_value

np.float64(2500.0)

In [ ]:
sales_data['Sales'].fillna(sales_data['Sales'].mean())

0    2500.0
1    2500.0
2    1800.0
3    3200.0
Name: Sales, dtype: float64

In [ ]:
sales_data          ## na is not updated

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,NaN,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

In [ ]:
sales_data['Sales']=sales_data['Sales'].fillna(mean_value)

In [ ]:
sales_data       ##  na is updated

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,2500.0,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

In [ ]:
sales_data[['Profit','Quantity']].fillna(18,axis=0) ##axis = 0 → operate down the rows (column-wise)
                                                    ##axis = 1 → operate across the columns (row-wise)

   Profit  Quantity
0   200.0       2.0
1   350.0       3.0
2    18.0      18.0
3   500.0       5.0

In [ ]:
sales_data['Sales'].describe()

count       4.000000
mean     2500.000000
std       571.547607
min      1800.000000
25%      2325.000000
50%      2500.000000
75%      2675.000000
max      3200.000000
Name: Sales, dtype: float64

In [ ]:
sales_data['Discount']

0    0.10
1     NaN
2    0.20
3    0.15
Name: Discount, dtype: float64

In [ ]:
sales_data['Discount'].ffill()     ## ffill it means forword fill

0    0.10
1    0.10
2    0.20
3    0.15
Name: Discount, dtype: float64

In [ ]:
sales_data['Discount'].bfill()  ## back fill

0    0.10
1    0.20
2    0.20
3    0.15
Name: Discount, dtype: float64

In [ ]:
sales_data

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,2500.0,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

In [ ]:
sales_data.dropna(how='any',axis=1)

  Order_ID   Sales
0  CA-1001  2500.0
1  CA-1002  2500.0
2  CA-1003  1800.0
3  CA-1004  3200.0

In [ ]:
sales_data.dropna(how='all',axis=1)

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,2500.0,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

In [ ]:
sales_data.dropna(how='any',axis=0)      ## axis omitted or not gives row wise

  Order_ID Customer_Name Region   Category   Sales  Profit  Discount  Quantity
0  CA-1001          John  South  Furniture  2500.0   200.0       0.1       2.0

In [ ]:
sales_data.dropna(how='all',axis=0)

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,2500.0,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

In [ ]:
import pandas as pd
import numpy as np
data = pd.DataFrame({
    "Order_ID": ["CA-1001", "CA-1002", "CA-1003", "CA-1004"],
    "Customer_Name": ["John", np.nan, "David", "Maria"],
    "Region": ["South", "East", np.nan, "West"],
    "Category": ["Furniture", "Technology", "Office Supplies", np.nan],
    "Sales": [2500, np.nan, 1800, 3200],
    "Profit": [200, 350, np.nan, 500],
    "Discount": [0.10, np.nan, 0.20, 0.15],
    "Quantity": [2, 3, np.nan, 5]
})

In [ ]:
sales_data=pd.DataFrame(data)

In [ ]:
sales_data

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,NaN,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

In [ ]:
sales_data.dropna(axis=0,how='any').shape

(1, 8)

In [ ]:
sales_data.dropna(axis=0,how='all').shape

(4, 8)

In [ ]:
sales_data.dropna(axis=1,how='any').shape

(4, 1)

In [ ]:
sales_data.dropna(axis=1,how='all').shape

(4, 8)

In [ ]:
sales_data

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,NaN,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

In [ ]:

import numpy as np
import pandas as pd

def null_value_treatments(sales_data,tv):
    null_value_percentage=(sales_data.isna().sum()/sales_data.shape[0])*100
    columns_droped=null_value_percentage[null_value_percentage>=25].index
    columns_filled=null_value_percentage[null_value_percentage<25].index
    print("original shape:",sales_data.shape)
    print("column dropped :",list(columns_droped))
    print("columns filled :",list(columns_filled))


    null_value_percentage

In [ ]:
null_value_percentage

NameError: name 'null_value_percentage' is not defined

In [ ]:
sales_data.memory_usage()

Index            132
Order_ID          32
Customer_Name     32
Region            32
Category          32
Sales             32
Profit            32
Discount          32
Quantity          32
dtype: int64

In [ ]:
original_data_frame=sales_data.memory_usage().sum()

In [ ]:
original_data_frame

np.int64(388)

In [ ]:
sales_data

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,NaN,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

In [ ]:
sales_data['Sales']

0    2500.0
1       NaN
2    1800.0
3    3200.0
Name: Sales, dtype: float64

In [ ]:
sales_data['Sales'].min()

1800.0

In [ ]:
sales_data['Sales'].dtypes

dtype('float64')

In [ ]:
import pandas as pd 
import numpy as np
df=pd.read_csv(r"C:\Users\ADMIN\Downloads\application_train.csv")

In [ ]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
import pandas as pd 
import numpy as np
df_data=pd.read_csv(r"C:\Users\ADMIN\Downloads\application_train.csv")

In [ ]:
print(df_data)

        SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0           100002       1         Cash loans           M            N
1           100003       0         Cash loans           F            N
2           100004       0    Revolving loans           M            Y
3           100006       0         Cash loans           F            N
4           100007       0         Cash loans           M            N
...            ...     ...                ...         ...          ...
307506      456251       0         Cash loans           M            N
307507      456252       0         Cash loans           F            N
307508      456253       0         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307510      456255       0         Cash loans           F            N

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
0                    Y             0          202500.0    406597.5
1                    N             0          270000.0   1293502.5
2                    Y             0           67500.0    135000.0
3                    Y             0          135000.0    312682.5
4                    Y             0          121500.0    513000.0
...                ...           ...               ...         ...
307506               N             0          157500.0    254700.0
307507               Y             0           72000.0    269550.0
307508               Y             0          153000.0    677664.0
307509               Y             0          171000.0    370107.0
307510               N             0          157500.0    675000.0

        AMT_ANNUITY  ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20  \
0           24700.5  ...                 0                0                0
1           35698.5  ...                 0                0                0
2            6750.0  ...                 0                0                0
3           29686.5  ...                 0                0                0
4           21865.5  ...                 0                0                0
...             ...  ...               ...              ...              ...
307506      27558.0  ...                 0                0                0
307507      12001.5  ...                 0                0                0
307508      29979.0  ...                 0                0                0
307509      20205.0  ...                 0                0                0
307510      49117.5  ...                 0                0                0

       FLAG_DOCUMENT_21 AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                     0                        0.0                       0.0
1                     0                        0.0                       0.0
2                     0                        0.0                       0.0
3                     0                        NaN                       NaN
4                     0                        0.0                       0.0
...                 ...                        ...                       ...
307506                0                        NaN                       NaN
307507                0                        NaN                       NaN
307508                0                        1.0                       0.0
307509                0                        0.0                       0.0
307510                0                        0.0                       0.0

        AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                              0.0                        0.0
1                              0.0                        0.0
2                              0.0                        0.0
3                              NaN                        NaN
4                              0.0                        0.0
...                            ...                        ...
307506                         NaN                        NaN
307507                         NaN                        NaN
307508                         0.0                        1.0
307509                         0.0                        0.0
307510                         0.0                        2.0

        AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR
0                             0.0                         1.0
1                             0.0                         0.0
2                             0.0                         0.0
3                             NaN                         NaN
4                             0.0                         0.0
...                           ...                         ...
307506                        NaN                         NaN
307507                        NaN                         NaN
307508                        0.0                         1.0
307509                        0.0                         0.0
307510                        0.0                         1.0

[307511 rows x 122 columns]

In [ ]:
df_data

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [ ]:
df_data.shape

(307511, 122)

In [ ]:
df_data.isna()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
307507,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
307508,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
307509,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
307510,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df_data.isna().sum()

SK_ID_CURR                        0
TARGET                            0
NAME_CONTRACT_TYPE                0
CODE_GENDER                       0
FLAG_OWN_CAR                      0
                              ...
AMT_REQ_CREDIT_BUREAU_DAY     41519
AMT_REQ_CREDIT_BUREAU_WEEK    41519
AMT_REQ_CREDIT_BUREAU_MON     41519
AMT_REQ_CREDIT_BUREAU_QRT     41519
AMT_REQ_CREDIT_BUREAU_YEAR    41519
Length: 122, dtype: int64

In [ ]:
df_data.isna().sum().sum()     ## for total null values

np.int64(9152465)

In [ ]:
num_col=df_data.select_dtypes(include='number')

In [ ]:
num_col

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,0,202500.0,406597.5,24700.5,351000.0,0.018801,-9461,-637,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-16765,-1188,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,0,67500.0,135000.0,6750.0,135000.0,0.010032,-19046,-225,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,0,135000.0,312682.5,29686.5,297000.0,0.008019,-19005,-3039,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,0,121500.0,513000.0,21865.5,513000.0,0.028663,-19932,-3038,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,0,157500.0,254700.0,27558.0,225000.0,0.032561,-9327,-236,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,0,72000.0,269550.0,12001.5,225000.0,0.025164,-20775,365243,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,0,153000.0,677664.0,29979.0,585000.0,0.005002,-14966,-7921,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,0,171000.0,370107.0,20205.0,319500.0,0.005313,-11961,-4786,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,0,157500.0,675000.0,49117.5,675000.0,0.046220,-16856,-1262,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [ ]:
obj_col=df_data.select_dtypes(include='object')

In [ ]:
obj_col

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,FONDKAPREMONT_MODE,HOUSETYPE_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE
0,Cash loans,M,N,Y,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,Laborers,WEDNESDAY,Business Entity Type 3,reg oper account,block of flats,"Stone, brick",No
1,Cash loans,F,N,N,Family,State servant,Higher education,Married,House / apartment,Core staff,MONDAY,School,reg oper account,block of flats,Block,No
2,Revolving loans,M,Y,Y,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,Laborers,MONDAY,Government,NaN,NaN,NaN,NaN
3,Cash loans,F,N,Y,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,Laborers,WEDNESDAY,Business Entity Type 3,NaN,NaN,NaN,NaN
4,Cash loans,M,N,Y,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,Core staff,THURSDAY,Religion,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,Cash loans,M,N,N,Unaccompanied,Working,Secondary / secondary special,Separated,With parents,Sales staff,THURSDAY,Services,reg oper account,block of flats,"Stone, brick",No
307507,Cash loans,F,N,Y,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,NaN,MONDAY,XNA,reg oper account,block of flats,"Stone, brick",No
307508,Cash loans,F,N,Y,Unaccompanied,Working,Higher education,Separated,House / apartment,Managers,THURSDAY,School,reg oper account,block of flats,Panel,No
307509,Cash loans,F,N,Y,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,Laborers,WEDNESDAY,Business Entity Type 1,NaN,block of flats,"Stone, brick",No
307510,Cash loans,F,N,N,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,Laborers,THURSDAY,Business Entity Type 3,NaN,block of flats,Panel,No

In [ ]:
null_counts = df_data.isnull().sum()
print(null_counts)

SK_ID_CURR                        0
TARGET                            0
NAME_CONTRACT_TYPE                0
CODE_GENDER                       0
FLAG_OWN_CAR                      0
                              ...
AMT_REQ_CREDIT_BUREAU_DAY     41519
AMT_REQ_CREDIT_BUREAU_WEEK    41519
AMT_REQ_CREDIT_BUREAU_MON     41519
AMT_REQ_CREDIT_BUREAU_QRT     41519
AMT_REQ_CREDIT_BUREAU_YEAR    41519
Length: 122, dtype: int64

In [ ]:
Q1 = df_data['AMT_CREDIT'].quantile(0.25)
Q3 = df_data['AMT_CREDIT'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df_data[(df_data['AMT_CREDIT'] < lower_bound) | (df_data['AMT_CREDIT'] > upper_bound)]

print(len(outliers))

6562

In [ ]:
df_data.memory_usage()

Index                             132
SK_ID_CURR                    2460088
TARGET                        2460088
NAME_CONTRACT_TYPE            2460088
CODE_GENDER                   2460088
                               ...
AMT_REQ_CREDIT_BUREAU_DAY     2460088
AMT_REQ_CREDIT_BUREAU_WEEK    2460088
AMT_REQ_CREDIT_BUREAU_MON     2460088
AMT_REQ_CREDIT_BUREAU_QRT     2460088
AMT_REQ_CREDIT_BUREAU_YEAR    2460088
Length: 123, dtype: int64

In [ ]:
df_data['AMT_CREDIT'].memory_usage()

2460220

In [ ]:
min_value=df_data['AMT_CREDIT'].min()
min_value

45000.0

In [ ]:
max_value=df_data['AMT_CREDIT'].max()
max_value

4050000.0

In [ ]:
median_value=df_data['AMT_CREDIT'].median()
median_value

513531.0

In [ ]:
np.finfo('float32').min

np.float32(-3.4028235e+38)

In [ ]:
np.finfo('float32').max

np.float32(3.4028235e+38)

In [ ]:
np.finfo('float64').min

np.float64(-1.7976931348623157e+308)

In [ ]:
np.finfo('float64').max

np.float64(1.7976931348623157e+308)

In [ ]:
if min_value > np.finfo('float32').min and max_value < np.finfo('float32').max:        
    print('float32')
elif min_value > np.finfo('float64').min and max_value< np.finfo('float64').max:
    print('float64')
else:
    print('sorry')

float32

In [ ]:
memory_used_original=df_data['AMT_CREDIT'].memory_usage(deep=True)/1024**2
memory_used_original

2.3462486267089844

In [ ]:
df_data['AMT_CREDIT']=pd.to_numeric(df_data['AMT_CREDIT'].astype('float32'))
df_data['AMT_CREDIT'].dtype

dtype('float32')

In [ ]:
memory_used_optimized=df_data.memory_used=df_data['AMT_CREDIT'].memory_usage(deep=True)/1024**2
memory_used_optimized

1.173187255859375

In [ ]:
optimized_percentage=memory_used_original-memory_used_optimized/memory_used_original*100
optimized_percentage

-47.65643406020519

In [21]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [22]:
df.shape

(9994, 21)

In [33]:
obj_col=df.select_dtypes(include='object')
obj_col

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
0,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase
1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,..."
2,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...
3,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table
4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle
9990,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...
9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone
9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5"""
9993,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou..."

In [30]:
obj_col.shape

(9994, 15)

In [28]:
num_col=df.select_dtypes(include='number')
num_col

      Row ID  Postal Code     Sales  Quantity  Discount    Profit
0          1        42420  261.9600         2      0.00   41.9136
1          2        42420  731.9400         3      0.00  219.5820
2          3        90036   14.6200         2      0.00    6.8714
3          4        33311  957.5775         5      0.45 -383.0310
4          5        33311   22.3680         2      0.20    2.5164
...      ...          ...       ...       ...       ...       ...
9989    9990        33180   25.2480         3      0.20    4.1028
9990    9991        92627   91.9600         2      0.00   15.6332
9991    9992        92627  258.5760         2      0.20   19.3932
9992    9993        92627   29.6000         4      0.00   13.3200
9993    9994        92683  243.1600         2      0.00   72.9480

[9994 rows x 6 columns]

In [4]:
import pandas as pd
df_apply_data = pd.DataFrame({
    'Number': [1, 2, 3, 4, 5],
    'Text': ['apple', 'banana', 'cherry', 'date', 'elderberry']
})
df_apply_data['Upper_text']=df_apply_data['Text'].str.upper()

In [5]:
df_apply_data

   Number        Text  Upper_text
0       1       apple       APPLE
1       2      banana      BANANA
2       3      cherry      CHERRY
3       4        date        DATE
4       5  elderberry  ELDERBERRY